### ISSUE TITLE
代码编译部署以后，从跟目录跳转到页面详情 左侧边栏不打开

### ISSUE THREAD

**Issue by linthan** [yuque-helper/book-front-end#2]
# 录屏详情
![GIF](https://user-images.githubusercontent.com/13914829/55373958-77a04600-5539-11e9-89cc-4e90a4e5c270.gif)

**Comment by cctv1005s** [comment]
我看一下

**Comment by cctv1005s** [comment]
你的源文档是哪一篇？可以给我发一个链接吗？另外点不开可以看一下浏览器报错吗？

**Comment by linthan** [comment]
@cctv1005s 

数据用的就是 https://github.com/yuque-helper/example-data 这里面的数据。
我把有字节点的菜单节点 移到了最前面
https://github.com/yuque-helper/example-data/blob/master/json/toc.json

你用yarn start 开发的时候是发现不了的。 要用yarn build了 以后。 再 serve（https://github.com/zeit/serve） 编译以后的目录。访问根目录就会出现这样的问题。

使用的环境是
window 10 
Google Chrome 已是最新版本
版本 73.0.3683.86（正式版本） （32 位）

**Comment by cctv1005s** [comment]
@linthan 你把你改过的 toc.json 的文件发出来看一下吧，我复现看一下

**Comment by linthan** [comment]
@cctv1005s 
[
  {
    "title": "子节点",
    "slug": "#",
    "depth": 1
  },
  {
    "title": "多图片",
    "slug": "hky8bv",
    "depth": 2
  },
  {
    "title": "文章内容互相引用",
    "slug": "ovwvbo",
    "depth": 2
  },
  {
    "title": "表格",
    "slug": "rq8m3g",
    "depth": 3
  },
  {
    "title": "节点4",
    "slug": "tit3gd",
    "depth": 4
  },
  {
    "title": "yuque2book - 超好用的文档工具",
    "slug": "qp74zh",
    "depth": 1
  },
  {
    "title": "直接跳转第三方链接",
    "slug": "https://www.yuque.com/yuque/help",
    "depth": 1
  },
  {
    "title": "链接到本身内容",
    "slug": "https://www.yuque.com/yuque-helper/example-data/ovwvbo",
    "depth": 1
  },
  {
    "title": "数学公式",
    "slug": "ru2pi5",
    "depth": 1
  },
  {
    "title": "附件测试",
    "slug": "qgd4yv",
    "depth": 1
  },
  {
    "title": "代码格式",
    "slug": "sal620",
    "depth": 1
  }
]
